### ISSUE TITLE
Sliders not working

### ISSUE THREAD

**Issue by s5zone** [kershner/screenBloom#27]
the sliders are not working for me to pick buffer, update speed and saturization. Chrome console:
Uncaught TypeError: $(...).colpick is not a function
    at colorPicker (screenBloom.js:650)
    at Object.screenBloom.init (screenBloom.js:44)
    at HTMLDocument.<anonymous> ((index):11110)
    at i (jquery-2.2.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.0.min.js:2)
    at Function.ready (jquery-2.2.0.min.js:2)
    at HTMLDocument.J (jquery-2.2.0.min.js:2)

**Comment by kershner** [comment]
Oh hey there - I bet I know what the issue is.  Are you upgrading from a previous version?  You'll want to clear your browser cache (press **CTRL + F5** if you're using Chrome).

The browser has cached a previous version of ScreenBloom's JS so it doesn't have to load it every time you visit the page.  However the JS was changed in the update, so it's looking for references that aren't there anymore.

Let me know if that does the trick!

**Comment by s5zone** [comment]
That did indeed fix it. Awesome response time! And thx for the help ;-) good job again!!!

**Comment by kershner** [comment]
Haha slow day at work =)

Just let me know if you run into any further issues!
