### ISSUE TITLE
Administrator Rights Needed

### ISSUE THREAD

**Issue by joemulray** [kershner/screenBloom#34]
```
An error occurred, please try again.
Error Text: Permission denied, administrator rights needed.. 
```

Anyone get this error when trying to run screenBloom, on macOS tried doing research couldn't find anything to solve.

**Comment by kershner** [comment]
Hey Joe,

Yeah a handful of people report getting this issue.  No clue what's causing the error because it's simply trying to create/read to a config file in the .app package, which the program should have full permission over, regardless of the actual permissions of the user account being used.

Two things to try:
- Move the screenBloom.app package into a directory you are sure your user has full permissions over (such as Documents or Downloads or Desktop)
- Open up terminal and explicitly run the program with the **sudo** command.

Let me know if either of those work for you.

**Comment by kershner** [comment]
Hey Joe,

I may have discovered and fixed the issue.  Pushed up a new Mac version to [the site](http://www.screenbloom.com).  Can you grab it and let me know if it resolves your issue?

Thanks for your patience!

**Comment by joemulray** [comment]
havent came across since sorry for the long responce :)
