### ISSUE TITLE
Error with black color

### ISSUE THREAD

**Issue by franckentien** [kershner/screenBloom#41]
I have an error when i have a black color on screen my hue LightStrips display white color. 
Every other colors was corect only this was ok but the dark was display with white light. 

I know they doesn't have black color but i want the light swich off when my screen is black. 

How can i correct it ? 
 
Thanks for you job

**Comment by kershner** [comment]
Hey there,

I think you're seeing expected behavior.  ScreenBloom ignores pixels that are too dark (or too light) as they can wash out the final average.  Because of this, if ScreenBloom is parsing an image that is extremely dark (I.E. the programming is will ignore ALL the pixels) then it will just spit out something like 255,255,255 - just some kind of default value.  If your min/max brightness are all the way up, you'll get a bright white light at this point.  The easiest "fix" is to just set your min brightness low, so when this behavior occurs the actual color doesn't matter because the Hues will be extremely dim.

As far as turning the lights off completely, unfortunately I've experimented with this functionality a few times and due to the way that the Hue bulbs work it's actually not feasible.  There is a bit of startup time associated with turning the lights fully off/on and if that happens rapidly it causes huge delays.  The solution to simply dim the lights down to the lowest min-brightness value is much more performant and works well, I think.

Let me know if you have any additional questions.

**Comment by franckentien** [comment]
Thanks i understand for doesn't switch off the light. 
I have excepted when my screen was totally dark for a transition for example my light brightness go to 1% for make like it was turn off. 

I have do a test with my windows CMD and notepad++ ans i saw the light level was different. 

But i have excepted have my brightness near 5% with my CMD program (totally dark) or actually i have my light at 39%. 

Any way to set the light a 1% when my screen is dark manually for example ? 

My brightness in screenbloom was to max 254 and min 1.  

Thanks

**Comment by kershner** [comment]
Sorry, I'm having a hard time understanding the question, could you possible rephrase it?

In case this is what you're after: each bulb has its own min/max brightness setting.

**Comment by franckentien** [comment]
Sorry for be difficult to understand. 

my question is: does it possible to edit something for have the light at le lower level of brightness when my screen is dark ? 

Actually when my screen was black i have my hue lightstrip in white with a brightness of 40% 
But does it possible to have the light in white but a < 10% of brightness ? 

Thanks

**Comment by kershner** [comment]
No worries man, hope to sort through your issue!

Are you saying that your screen is black but the lights only dim to about 40% or so?  If that's the case, I'd double check that your selected bulb doesn't have a min-brightness set above your global min.

**Comment by franckentien** [comment]
You have right, 
I have check and my blubs was all at the max brightness 
an error of me or a config i don't know, 

Thanks for your help

**Comment by jespertheend** [comment]
Hey @kershner , I have a bit of an unusual setup. I have MiLights and I'm emulating the hue bridge using [diyHue](https://github.com/mariusmotea/diyHue). I'm not sure what the actual hue lights look like when their brightness are set to 1%, but mine are still really bright. Also I think turning my lights off completely doesn't have as much of a delay as the official hue lights. (Though my lights don't seem as responsive as some of the videos I've seen anyway).

Either way, I'd really like to try out the turning lights off completely functionality. Not sure how difficult it would be to add this as a setting so people can turn it on if they want to.
I can also do a PR if necessary.
