### ISSUE TITLE
Fullscreen Support on Windows Games

### ISSUE THREAD

**Issue by MrDrache333** [kershner/screenBloom#63]
It is normal that the Lights turn off when im entering an Fullscreen Game?

**Comment by kershner** [comment]
Yep, that's normal.  ScreenBloom only supports windowed mode, because that's the only way that Python has to get at the on-screen pixels.  Fullscreen goes through a different buffer and I'm not aware of any Pythonic way to get the pixels that way.

So instead of rewriting the entire application in a different language, I decided this one limitation is perfectly fine.  Lemme know if you have any other questions!
