### ISSUE TITLE
Multiple monitors don't work on mac

### ISSUE THREAD

**Issue by Mellbourn** [kershner/screenBloom#77]
When I use screenBloom on my Macbook Pro, only the laptop monitor seems to be used when determining color. I have two other monitors connected, and changing what they display does not alter the lighting at all.
I see on screenbloom.com that there should be a `Choose Display` option, but it is not shown when I run screenbloom. If I click on 'Screen Zones' only the laptop monitor is shown.

ScreenBloolm version 2.2
macOS High Sierra version 10.13.3
Macbook Pro, Retina, 15-oinch, Mid 2015.

Thanks for an awesome app!

**Comment by kershner** [comment]
Hey there!

Unfortunately multiple monitors is not supported on the Mac version.  There are a couple of inconsistencies like that due to there not being Mac support for some of the libraries that ScreenBloom uses.

Sorry for the disappointing answer - I will try and make this limitation more visible somewhere on the website.
